### ISSUE TITLE
Geth: Load Testing

### ISSUE THREAD

**Issue by hermanjunge** [ConsenSys/infura#30]

**Comment by hermanjunge** [comment]
## SECURITY RULES

* There are not network security rules among the subnets. Just the minimal for the internet exposed ones.

## GETH DAEMON SET

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: mainnet
spec:
  template:
    metadata:
      labels:
        app: mainnet
    spec:
      nodeSelector:
        role: mainnet
      containers:
        - name: geth
          image: consensysllc/geth
          command:
            - "/usr/bin/geth"
            - "--rpc"
            - "--rpcaddr"
            - "0.0.0.0"
            - "--rpccorsdomain"
            - "*"
          ports:
            - hostPort: 8545
              containerPort: 8545
              name: rpc
          volumeMounts:
            - mountPath: /root/.ethereum
              name: dot-eth
      volumes:
        - hostPath:
            path: /var/infura/mainnet
          name: dot-eth
```

* Dockerfile

```
FROM ubuntu:wily

MAINTAINER Herman Junge <herman.junge@consensys.net>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -q -y \
    && apt-get upgrade -q -y \
    && apt-get dist-upgrade -q -y \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 923F6CA9 \
    && echo "deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu wily main" | tee -a /etc/apt/sources.list.d/ethereum.list \
    && apt-get update -q -y \
    && apt-get install -y geth solc

EXPOSE 8545
EXPOSE 30303

ENTRYPOINT ["/usr/bin/geth"]
```
